// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXIqFFRDcoggp42HumK_oOGc8cAbpGVs0',
    appId: '1:823233113152:web:6565f42bcee8b4acb883a5',
    messagingSenderId: '823233113152',
    projectId: 'lotex-4890a',
    authDomain: 'lotex-4890a.firebaseapp.com',
    storageBucket: 'lotex-4890a.firebasestorage.app',
    measurementId: 'G-NP3NFWETVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlPOLUuBt__ppa-TQtizFCjwNcQU0DNQ',
    appId: '1:823233113152:android:3a10dcde54334bd2b883a5',
    messagingSenderId: '823233113152',
    projectId: 'lotex-4890a',
    storageBucket: 'lotex-4890a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQSla4mzDuocuFYj-MMMt6FBLNSBkPaXg',
    appId: '1:823233113152:ios:47970db92db8909fb883a5',
    messagingSenderId: '823233113152',
    projectId: 'lotex-4890a',
    storageBucket: 'lotex-4890a.firebasestorage.app',
    iosBundleId: 'com.example.lotex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQSla4mzDuocuFYj-MMMt6FBLNSBkPaXg',
    appId: '1:823233113152:ios:47970db92db8909fb883a5',
    messagingSenderId: '823233113152',
    projectId: 'lotex-4890a',
    storageBucket: 'lotex-4890a.firebasestorage.app',
    iosBundleId: 'com.example.lotex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXIqFFRDcoggp42HumK_oOGc8cAbpGVs0',
    appId: '1:823233113152:web:68c71885e4edb69db883a5',
    messagingSenderId: '823233113152',
    projectId: 'lotex-4890a',
    authDomain: 'lotex-4890a.firebaseapp.com',
    storageBucket: 'lotex-4890a.firebasestorage.app',
    measurementId: 'G-HWCD3BQZY1',
  );

}